name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
    - name: cabal build
      run: cabal build

  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
    - name: cabal build
      run: cabal build

  build-windows:
    runs-on: windows-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: nmake
      run: nmake -f Makefile.windows
    - name: nmake exampletest
      run: nmake -f Makefile.windows exampletest
