name: MicroHs CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
    - name: cabal build
      run: cabal build

  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
    - name: cabal build
      run: cabal build

  build-windows:
    runs-on: windows-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: nmake
      run: nmake -f Makefile.windows
    - name: nmake exampletest
      run: nmake -f Makefile.windows exampletest

  build-linux-32:
    runs-on: ubuntu-latest
    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: x86
        branch: v3.15
        packages: >
          build-base
          gcc
          make
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make CONF=unix-32
      shell: alpine.sh {0}
    - name: make mhseval
      run: make CONF=unix-32 bin/mhseval
      shell: alpine.sh {0}
    - name: simple test
      run: bin/mhseval +RTS -v -v -v -v -rcomb/simple.comb"
      shell: alpine.sh {0}
#    - name: make everytestmhs
#      run: make CONF=unix-32 everytestmhs
#      shell: alpine.sh {0}
